### ISSUE TITLE
Markbot Outline Issue

### ISSUE THREAD

**Issue by faithebert** [faithebert/arrrgenes-treasure-tours#1]
@muxlowc

Hey again! I keep getting this message and cannot figure out what to change to fix it. Everything else goes through Markbot fine, just not this. Thanks, again!

<img width="505" alt="Screen Shot 2020-04-01 at 9 37 44 PM" src="https://user-images.githubusercontent.com/55109632/78202024-2afb8d80-7461-11ea-9c7f-187c428ca71a.png">

**Comment by muxlowc** [comment]
@faithebert 
You're going to have to add an outline-color to your .btn-banner:hover &
.btn-banner:focus in your css. So that means when your button in your banner is in focus or hovered, it still needs to have enough of a contrast on that dark background

**Comment by faithebert** [comment]
I had been putting an outline on the .nav a span tags for hover and focus and that didn't work. So I put the outline on the .btn-banner focus and hover, that still didn't appease him. Finally I just put the outline on the nav a, without the focus or hover and that worked. Thanks again for your help and answering so quickly!
